build-dir: dist
# entries:
#   - from: tsconfig.json
#     to: config/tsconfig-base.jsonc
#   - from: babel.js
#     to: config/babel.js
#   - from: eslint.js
#     to: config/eslint.js
#   - from: jest.js
#     to: config/jest.js
#   - from: package-scripts.js
#     to: config/package-scripts.js
